CREATE TABLE "AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);


CREATE TABLE "AspNetUsers" (
    "Id" text NOT NULL,
    "DisplayName" text NOT NULL,
    "Kind" text NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);


CREATE TABLE "CatalogServices" (
    "Id" uuid NOT NULL,
    "OwnerId" text NOT NULL,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "BasePrice" numeric(14,2) NOT NULL,
    "EstimatedDays" integer NOT NULL,
    CONSTRAINT "PK_CatalogServices" PRIMARY KEY ("Id")
);


CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);


CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "BusinessLogos" (
    "OwnerId" text NOT NULL,
    "DataUrl" text NOT NULL,
    CONSTRAINT "PK_BusinessLogos" PRIMARY KEY ("OwnerId"),
    CONSTRAINT "FK_BusinessLogos_AspNetUsers_OwnerId" FOREIGN KEY ("OwnerId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "BusinessProfiles" (
    "OwnerId" text NOT NULL,
    "BusinessName" text NOT NULL,
    "ResponsibleName" text NOT NULL,
    "TaxId" text NOT NULL,
    "Email" text NOT NULL,
    "Phone" text NOT NULL,
    "Website" text NOT NULL,
    "Address" text NOT NULL,
    CONSTRAINT "PK_BusinessProfiles" PRIMARY KEY ("OwnerId"),
    CONSTRAINT "FK_BusinessProfiles_AspNetUsers_OwnerId" FOREIGN KEY ("OwnerId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Clients" (
    "Id" uuid NOT NULL,
    "OwnerId" text NOT NULL,
    "UserId" text,
    "Name" text NOT NULL,
    "Company" text NOT NULL,
    "Email" text NOT NULL,
    "Phone" text NOT NULL,
    "Notes" text NOT NULL,
    CONSTRAINT "PK_Clients" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Clients_AspNetUsers_OwnerId" FOREIGN KEY ("OwnerId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Clients_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "EmailChallenges" (
    "Id" uuid NOT NULL,
    "UserId" text NOT NULL,
    "Purpose" text NOT NULL,
    "CodeHash" text NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "Attempts" integer NOT NULL,
    "UsedAt" timestamp with time zone,
    "InvitationId" uuid,
    CONSTRAINT "PK_EmailChallenges" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EmailChallenges_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Invitations" (
    "Id" uuid NOT NULL,
    "ClientId" uuid NOT NULL,
    "TokenHash" text NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "UsedAt" timestamp with time zone,
    CONSTRAINT "PK_Invitations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Invitations_Clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES "Clients" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Quotes" (
    "Id" uuid NOT NULL,
    "OwnerId" text NOT NULL,
    "ClientId" uuid NOT NULL,
    "Title" text NOT NULL,
    "Status" text NOT NULL,
    "ValidUntil" date NOT NULL,
    "Discount" numeric(14,2) NOT NULL,
    "Terms" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Quotes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Quotes_Clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES "Clients" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "Projects" (
    "Id" uuid NOT NULL,
    "OwnerId" text NOT NULL,
    "ClientId" uuid NOT NULL,
    "QuoteId" uuid,
    "Title" text NOT NULL,
    "Stage" text NOT NULL,
    "DueDate" date NOT NULL,
    "Value" numeric(14,2) NOT NULL,
    "ClientPending" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Projects" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Projects_Clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES "Clients" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Projects_Quotes_QuoteId" FOREIGN KEY ("QuoteId") REFERENCES "Quotes" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "QuoteLine" (
    "Id" uuid NOT NULL,
    "QuoteId" uuid NOT NULL,
    "Description" text NOT NULL,
    "Quantity" integer NOT NULL,
    "UnitPrice" numeric(14,2) NOT NULL,
    CONSTRAINT "PK_QuoteLine" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_QuoteLine_Quotes_QuoteId" FOREIGN KEY ("QuoteId") REFERENCES "Quotes" ("Id") ON DELETE CASCADE
);


CREATE TABLE "QuoteLogos" (
    "QuoteId" uuid NOT NULL,
    "DataUrl" text NOT NULL,
    CONSTRAINT "PK_QuoteLogos" PRIMARY KEY ("QuoteId"),
    CONSTRAINT "FK_QuoteLogos_Quotes_QuoteId" FOREIGN KEY ("QuoteId") REFERENCES "Quotes" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Deliveries" (
    "Id" uuid NOT NULL,
    "ProjectId" uuid NOT NULL,
    "Title" text NOT NULL,
    "Url" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Deliveries" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Deliveries_Projects_ProjectId" FOREIGN KEY ("ProjectId") REFERENCES "Projects" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Installments" (
    "Id" uuid NOT NULL,
    "ProjectId" uuid NOT NULL,
    "Label" text NOT NULL,
    "Amount" numeric(14,2) NOT NULL,
    "DueDate" date NOT NULL,
    "PaidAt" timestamp with time zone,
    CONSTRAINT "PK_Installments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Installments_Projects_ProjectId" FOREIGN KEY ("ProjectId") REFERENCES "Projects" ("Id") ON DELETE CASCADE
);


CREATE TABLE "ProjectTasks" (
    "Id" uuid NOT NULL,
    "ProjectId" uuid NOT NULL,
    "Title" text NOT NULL,
    "DueDate" date NOT NULL,
    "Done" boolean NOT NULL,
    CONSTRAINT "PK_ProjectTasks" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ProjectTasks_Projects_ProjectId" FOREIGN KEY ("ProjectId") REFERENCES "Projects" ("Id") ON DELETE CASCADE
);


CREATE TABLE "ProjectUpdates" (
    "Id" uuid NOT NULL,
    "ProjectId" uuid NOT NULL,
    "Text" text NOT NULL,
    "Internal" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ProjectUpdates" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ProjectUpdates_Projects_ProjectId" FOREIGN KEY ("ProjectId") REFERENCES "Projects" ("Id") ON DELETE CASCADE
);


CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");


CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");


CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");


CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");


CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");


CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");


CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");


CREATE UNIQUE INDEX "IX_Clients_OwnerId_Email" ON "Clients" ("OwnerId", "Email");


CREATE INDEX "IX_Clients_UserId" ON "Clients" ("UserId");


CREATE INDEX "IX_Deliveries_ProjectId" ON "Deliveries" ("ProjectId");


CREATE INDEX "IX_EmailChallenges_UserId" ON "EmailChallenges" ("UserId");


CREATE INDEX "IX_Installments_ProjectId" ON "Installments" ("ProjectId");


CREATE INDEX "IX_Invitations_ClientId" ON "Invitations" ("ClientId");


CREATE UNIQUE INDEX "IX_Invitations_TokenHash" ON "Invitations" ("TokenHash");


CREATE INDEX "IX_Projects_ClientId" ON "Projects" ("ClientId");


CREATE UNIQUE INDEX "IX_Projects_QuoteId" ON "Projects" ("QuoteId");


CREATE INDEX "IX_ProjectTasks_ProjectId" ON "ProjectTasks" ("ProjectId");


CREATE INDEX "IX_ProjectUpdates_ProjectId" ON "ProjectUpdates" ("ProjectId");


CREATE INDEX "IX_QuoteLine_QuoteId" ON "QuoteLine" ("QuoteId");


CREATE INDEX "IX_Quotes_ClientId" ON "Quotes" ("ClientId");


